// dnf 规范 — DNF 软件包管理器 (RHEL/Rocky/Alma/Fedora)
const completionSpec = {
  name: "dnf",
  description: "DNF 软件包管理器 (RHEL/Rocky/Alma/Fedora)",
  subcommands: [
    { name: "install", description: "安装软件包", args: { name: "软件包", isVariadic: true } },
    { name: "remove", description: "卸载软件包", args: { name: "软件包", isVariadic: true } },
    { name: "upgrade", description: "升级已安装的软件包", args: { name: "软件包", isOptional: true, isVariadic: true } },
    { name: "update", description: "升级命令的别名", args: { name: "软件包", isOptional: true, isVariadic: true } },
    { name: "autoremove", description: "移除作为依赖安装但已不需要的软件包" },
    { name: "reinstall", description: "重新安装软件包", args: { name: "软件包", isVariadic: true } },
    { name: "downgrade", description: "降级软件包", args: { name: "软件包", isVariadic: true } },
    { name: "distro-sync", description: "同步已安装软件包到可用的最新版本", args: { name: "软件包", isOptional: true, isVariadic: true } },
    { name: "swap", description: "在一次操作中卸载一个包并安装另一个包", args: [
      { name: "remove-spec" },
      { name: "install-spec" },
    ]},
    { name: "search", description: "通过关键字搜索包详情", args: { name: "关键字", isVariadic: true } },
    { name: "info", description: "显示软件包详情", args: { name: "软件包", isVariadic: true } },
    { name: "list", description: "列出软件包", subcommands: [
      { name: "installed", description: "列出已安装的软件包" },
      { name: "available", description: "列出可用的软件包" },
      { name: "updates", description: "列出可更新的软件包" },
      { name: "obsoletes", description: "列出已被废弃的软件包" },
      { name: "all", description: "列出所有软件包" },
    ]},
    { name: "provides", description: "查找哪个软件包提供了某个文件/功能", args: { name: "功能" } },
    { name: "clean", description: "清理缓存数据", subcommands: [
      { name: "all", description: "清理所有缓存数据" },
      { name: "packages", description: "清理缓存的软件包" },
      { name: "metadata", description: "清理缓存的元数据" },
      { name: "dbcache", description: "清理数据库缓存数据" },
      { name: "expire-cache", description: "使缓存过期" },
    ]},
    { name: "makecache", description: "生成元数据缓存" },
    { name: "repolist", description: "显示已配置的软件源", subcommands: [
      { name: "all", description: "列出所有源" },
      { name: "enabled", description: "列出启用的源" },
      { name: "disabled", description: "列出已禁用的源" },
    ]},
    { name: "repoinfo", description: "显示仓库信息" },
    { name: "history", description: "查看和管理 DNF 事务历史", subcommands: [
      { name: "list", description: "列出事务" },
      { name: "info", description: "显示事务详情", args: { name: "编号" } },
      { name: "undo", description: "撤销某个事务", args: { name: "编号" } },
      { name: "redo", description: "重做某个事务", args: { name: "编号" } },
      { name: "rollback", description: "回滚到先前的事务", args: { name: "编号" } },
    ]},
    { name: "group", description: "管理软件包组", subcommands: [
      { name: "install", description: "安装软件包组", args: { name: "组" } },
      { name: "remove", description: "删除软件包组", args: { name: "组" } },
      { name: "list", description: "列出可用的软件包组" },
      { name: "info", description: "显示软件包组详情", args: { name: "组" } },
      { name: "upgrade", description: "升级软件包组", args: { name: "组", isOptional: true } },
    ]},
    { name: "module", description: "管理应用流模块", subcommands: [
      { name: "list", description: "列出模块", subcommands: [
        { name: "all", description: "列出所有模块" },
        { name: "enabled", description: "列出已启用的模块" },
        { name: "disabled", description: "列出已禁用的模块" },
        { name: "installed", description: "列出已安装的模块" },
      ]},
      { name: "info", description: "显示模块详情", args: { name: "模块", isVariadic: true } },
      { name: "install", description: "安装模块配置文件", args: { name: "模块", isVariadic: true } },
      { name: "remove", description: "删除已安装的模块配置文件", args: { name: "模块", isVariadic: true } },
      { name: "enable", description: "启用模块流", args: { name: "模块", isVariadic: true } },
      { name: "disable", description: "禁用模块", args: { name: "模块", isVariadic: true } },
      { name: "reset", description: "重置模块状态", args: { name: "模块", isVariadic: true } },
      { name: "update", description: "更新已安装的模块", args: { name: "模块", isOptional: true, isVariadic: true } },
    ]},
    { name: "check-update", description: "检查可用的软件包升级" },
    { name: "check-upgrade", description: "check-update命令别名" },
  ],
  options: [
    { name: "-y", description: "全部回答“是”以自动进行操作" },
    { name: "-q", description: "安静模式" },
    { name: "-v", description: "详细模式" },
    { name: "--enablerepo", description: "启用一个仓库", args: { name: "仓库" } },
    { name: "--disablerepo", description: "禁用一个仓库", args: { name: "仓库" } },
    { name: "--nogpgcheck", description: "关闭GPG签名检查" },
    { name: "--skip-broken", description: "跳过依赖问题的软件包" },
    { name: "--showduplicates", description: "显示仓库中重复的软件包" },
    { name: "--installroot", description: "设置安装根目录", args: { name: "路径", template: "folders" } },
    { name: "-C", description: "完全从系统缓存中运行" },
    { name: "--security", description: "只包括与安全相关的软件包" },
    { name: ["-h", "--help"], description: "显示帮助信息" },
  ],
};

export default completionSpec;
