// docker 规范 — Docker 容器引擎
const completionSpec = {
  name: "docker",
  description: "Docker 容器引擎",
  subcommands: [
    { name: "run", description: "在新容器中运行命令", args: [
      { name: "镜像" },
      { name: "命令", isOptional: true, isVariadic: true },
    ], options: [
      { name: ["-d", "--detach"], description: "在后台运行容器并打印容器 ID" },
      { name: "-it", description: "交互式终端（-i 与 -t 的组合）" },
      { name: ["-i", "--interactive"], description: "即使未附加也保持 STDIN 打开" },
      { name: ["-t", "--tty"], description: "分配一个伪终端" },
      { name: "--name", description: "为容器指定名称", args: { name: "名称" } },
      { name: ["-p", "--publish"], description: "将容器端口发布到主机", args: { name: "主机端口:容器端口" } },
      { name: ["-P", "--publish-all"], description: "将所有暴露端口发布到随机端口" },
      { name: ["-e", "--env"], description: "设置环境变量", args: { name: "KEY=VALUE" } },
      { name: "--env-file", description: "从文件读取环境变量", args: { name: "文件", template: "filepaths" } },
      { name: ["-v", "--volume"], description: "绑定挂载卷", args: { name: "主机路径:容器路径" } },
      { name: "--rm", description: "容器退出后自动删除" },
      { name: "--network", description: "将容器连接到指定网络", args: { name: "网络" } },
      { name: ["-w", "--workdir"], description: "设置容器内工作目录", args: { name: "路径" } },
      { name: ["-u", "--user"], description: "指定用户名或 UID", args: { name: "用户" } },
      { name: "--restart", description: "容器退出时的重启策略", args: { name: "策略", suggestions: ["no", "on-failure", "always", "unless-stopped"] } },
      { name: "--privileged", description: "赋予容器扩展权限" },
      { name: "--entrypoint", description: "覆盖镜像的默认 ENTRYPOINT", args: { name: "命令" } },
      { name: ["-m", "--memory"], description: "内存限制", args: { name: "大小" } },
      { name: "--cpus", description: "CPU 数量限制", args: { name: "数量" } },
      { name: "--pull", description: "运行前拉取镜像", args: { name: "策略", suggestions: ["always", "missing", "never"] } },
      { name: "--platform", description: "指定目标平台", args: { name: "平台" } },
    ]},
    { name: "exec", description: "在运行中的容器内执行命令", args: [
      { name: "容器" },
      { name: "命令", isVariadic: true },
    ], options: [
      { name: "-it", description: "交互式终端（-i 与 -t 的组合）" },
      { name: ["-i", "--interactive"], description: "即使未附加也保持 STDIN 打开" },
      { name: ["-t", "--tty"], description: "分配一个伪终端" },
      { name: ["-d", "--detach"], description: "在后台运行命令" },
      { name: ["-e", "--env"], description: "设置环境变量", args: { name: "KEY=VALUE" } },
      { name: ["-u", "--user"], description: "指定用户名或 UID", args: { name: "用户" } },
      { name: ["-w", "--workdir"], description: "设置容器内工作目录", args: { name: "路径" } },
      { name: "--privileged", description: "赋予命令扩展权限" },
    ]},
    { name: "ps", description: "列出容器", options: [
      { name: ["-a", "--all"], description: "显示所有容器（默认只显示运行中的）" },
      { name: ["-q", "--quiet"], description: "只显示容器 ID" },
      { name: ["-s", "--size"], description: "显示容器文件总大小" },
      { name: ["-f", "--filter"], description: "按条件过滤输出", args: { name: "条件" } },
      { name: "--format", description: "使用 Go 模板美化输出", args: { name: "模板" } },
      { name: ["-n", "--last"], description: "显示最近创建的 n 个容器", args: { name: "数量" } },
      { name: ["-l", "--latest"], description: "显示最近创建的一个容器" },
      { name: "--no-trunc", description: "不截断输出" },
    ]},
    { name: "logs", description: "获取容器日志", args: { name: "容器" }, options: [
      { name: ["-f", "--follow"], description: "持续跟踪日志输出" },
      { name: ["-t", "--timestamps"], description: "显示时间戳" },
      { name: ["-n", "--tail"], description: "从日志末尾显示指定行数", args: { name: "行数" } },
      { name: "--since", description: "显示指定时间之后的日志", args: { name: "时间" } },
      { name: "--until", description: "显示指定时间之前的日志", args: { name: "时间" } },
      { name: "--details", description: "显示日志的额外详情" },
    ]},
    { name: "start", description: "启动一个或多个已停止的容器", args: { name: "容器", isVariadic: true }, options: [
      { name: ["-a", "--attach"], description: "附加 STDOUT/STDERR 并转发信号" },
      { name: ["-i", "--interactive"], description: "附加容器的 STDIN" },
    ]},
    { name: "stop", description: "停止一个或多个运行中的容器", args: { name: "容器", isVariadic: true }, options: [
      { name: ["-t", "--time"], description: "强制杀死前等待的秒数（默认 10）", args: { name: "秒" } },
    ]},
    { name: "restart", description: "重启一个或多个容器", args: { name: "容器", isVariadic: true }, options: [
      { name: ["-t", "--time"], description: "强制杀死前等待的秒数（默认 10）", args: { name: "秒" } },
    ]},
    { name: "kill", description: "杀死一个或多个运行中的容器", args: { name: "容器", isVariadic: true }, options: [
      { name: ["-s", "--signal"], description: "发送给容器的信号（默认 KILL）", args: { name: "信号" } },
    ]},
    { name: "rm", description: "删除一个或多个容器", args: { name: "容器", isVariadic: true }, options: [
      { name: ["-f", "--force"], description: "强制删除运行中的容器（使用 SIGKILL）" },
      { name: ["-v", "--volumes"], description: "同时删除容器关联的匿名卷" },
      { name: ["-l", "--link"], description: "删除指定的链接" },
    ]},
    { name: "pause", description: "暂停一个或多个容器内的所有进程", args: { name: "容器", isVariadic: true } },
    { name: "unpause", description: "恢复一个或多个容器内被暂停的进程", args: { name: "容器", isVariadic: true } },
    { name: "attach", description: "将本地标准输入/输出/错误附加到运行中的容器", args: { name: "容器" }, options: [
      { name: "--no-stdin", description: "不附加 STDIN" },
      { name: "--sig-proxy", description: "将收到的信号代理给进程（默认开启）" },
    ]},
    { name: "inspect", description: "返回 Docker 对象的底层信息", args: { name: "名称或ID", isVariadic: true }, options: [
      { name: ["-f", "--format"], description: "使用 Go 模板格式化输出", args: { name: "模板" } },
      { name: ["-s", "--size"], description: "若对象为容器则显示文件总大小" },
      { name: "--type", description: "按指定类型返回 JSON", args: { name: "类型" } },
    ]},
    { name: "top", description: "显示容器中正在运行的进程", args: { name: "容器" } },
    { name: "stats", description: "实时显示容器资源使用统计", args: { name: "容器", isOptional: true, isVariadic: true }, options: [
      { name: ["-a", "--all"], description: "显示所有容器（默认只显示运行中的）" },
      { name: "--no-stream", description: "禁用流式统计，只拉取第一次结果" },
      { name: "--no-trunc", description: "不截断输出" },
      { name: "--format", description: "使用 Go 模板美化输出", args: { name: "模板" } },
    ]},
    { name: "port", description: "列出容器的端口映射", args: [
      { name: "容器" },
      { name: "端口", isOptional: true },
    ]},
    { name: "rename", description: "重命名容器", args: [
      { name: "容器" },
      { name: "新名称" },
    ]},
    { name: "update", description: "更新一个或多个容器的配置", args: { name: "容器", isVariadic: true }, options: [
      { name: ["-m", "--memory"], description: "内存限制", args: { name: "大小" } },
      { name: "--cpus", description: "CPU 数量限制", args: { name: "数量" } },
      { name: "--restart", description: "容器退出时的重启策略", args: { name: "策略" } },
    ]},
    { name: "wait", description: "阻塞直到一个或多个容器停止，然后打印退出码", args: { name: "容器", isVariadic: true } },
    { name: "create", description: "创建一个新容器（不启动）", args: [
      { name: "镜像" },
      { name: "命令", isOptional: true, isVariadic: true },
    ], options: [
      { name: "--name", description: "为容器指定名称", args: { name: "名称" } },
      { name: ["-p", "--publish"], description: "将容器端口发布到主机", args: { name: "主机端口:容器端口" } },
      { name: ["-e", "--env"], description: "设置环境变量", args: { name: "KEY=VALUE" } },
      { name: ["-v", "--volume"], description: "绑定挂载卷", args: { name: "主机路径:容器路径" } },
      { name: ["-i", "--interactive"], description: "即使未附加也保持 STDIN 打开" },
      { name: ["-t", "--tty"], description: "分配一个伪终端" },
    ]},
    { name: "cp", description: "在容器与本地文件系统之间复制文件/目录", args: { name: "源路径 目标路径" }, options: [
      { name: ["-a", "--archive"], description: "归档模式（复制所有 uid/gid 信息）" },
      { name: ["-L", "--follow-link"], description: "始终跟随源路径中的符号链接" },
    ]},
    { name: "diff", description: "检查容器文件系统上的文件或目录变更", args: { name: "容器" } },
    { name: "commit", description: "根据容器的变更创建新镜像", args: [
      { name: "容器" },
      { name: "仓库:标签", isOptional: true },
    ], options: [
      { name: ["-a", "--author"], description: "作者信息", args: { name: "作者" } },
      { name: ["-m", "--message"], description: "提交说明", args: { name: "说明" } },
      { name: ["-c", "--change"], description: "对创建的镜像应用 Dockerfile 指令", args: { name: "指令" } },
    ]},
    { name: "export", description: "将容器文件系统导出为 tar 归档", args: { name: "容器" }, options: [
      { name: ["-o", "--output"], description: "写入文件而不是 STDOUT", args: { name: "文件", template: "filepaths" } },
    ]},
    { name: "images", description: "列出镜像", args: { name: "仓库:标签", isOptional: true }, options: [
      { name: ["-a", "--all"], description: "显示所有镜像（默认隐藏中间层）" },
      { name: ["-q", "--quiet"], description: "只显示镜像 ID" },
      { name: ["-f", "--filter"], description: "按条件过滤输出", args: { name: "条件" } },
      { name: "--format", description: "使用 Go 模板美化输出", args: { name: "模板" } },
      { name: "--digests", description: "显示摘要（digest）" },
      { name: "--no-trunc", description: "不截断输出" },
    ]},
    { name: "pull", description: "从仓库拉取镜像", args: { name: "镜像[:标签]" }, options: [
      { name: ["-a", "--all-tags"], description: "下载仓库中所有带标签的镜像" },
      { name: ["-q", "--quiet"], description: "抑制详细输出" },
      { name: "--platform", description: "指定目标平台", args: { name: "平台" } },
    ]},
    { name: "push", description: "将镜像推送到仓库", args: { name: "镜像[:标签]" }, options: [
      { name: ["-a", "--all-tags"], description: "推送仓库中所有带标签的镜像" },
      { name: ["-q", "--quiet"], description: "抑制详细输出" },
    ]},
    { name: "build", description: "根据 Dockerfile 构建镜像", args: { name: "路径", template: "folders" }, options: [
      { name: ["-t", "--tag"], description: "镜像名称及可选标签（name:tag）", args: { name: "名称:标签" } },
      { name: ["-f", "--file"], description: "Dockerfile 路径（默认为 PATH/Dockerfile）", args: { name: "文件", template: "filepaths" } },
      { name: "--no-cache", description: "构建时不使用缓存" },
      { name: "--build-arg", description: "设置构建时变量", args: { name: "KEY=VALUE" } },
      { name: "--target", description: "设置要构建的目标阶段", args: { name: "阶段" } },
      { name: "--platform", description: "指定目标平台", args: { name: "平台" } },
      { name: ["-q", "--quiet"], description: "抑制构建输出，成功后只打印镜像 ID" },
      { name: "--pull", description: "始终尝试拉取更新版本的镜像" },
      { name: "--progress", description: "设置进度输出类型", args: { name: "类型", suggestions: ["auto", "plain", "tty"] } },
    ]},
    { name: "rmi", description: "删除一个或多个镜像", args: { name: "镜像", isVariadic: true }, options: [
      { name: ["-f", "--force"], description: "强制删除镜像" },
      { name: "--no-prune", description: "不删除未打标签的父镜像" },
    ]},
    { name: "tag", description: "为源镜像创建指向它的目标标签", args: { name: "源镜像[:标签] 目标镜像[:标签]" } },
    { name: "save", description: "将一个或多个镜像保存为 tar 归档", args: { name: "镜像", isVariadic: true }, options: [
      { name: ["-o", "--output"], description: "写入文件而不是 STDOUT", args: { name: "文件", template: "filepaths" } },
    ]},
    { name: "load", description: "从 tar 归档或 STDIN 加载镜像", options: [
      { name: ["-i", "--input"], description: "从 tar 文件读取而不是 STDIN", args: { name: "文件", template: "filepaths" } },
      { name: ["-q", "--quiet"], description: "抑制加载输出" },
    ]},
    { name: "history", description: "显示镜像的历史层", args: { name: "镜像" }, options: [
      { name: ["-H", "--human"], description: "以人类可读格式打印大小和日期（默认开启）" },
      { name: ["-q", "--quiet"], description: "只显示镜像 ID" },
      { name: "--no-trunc", description: "不截断输出" },
    ]},
    { name: "import", description: "从 tarball 导入内容以创建文件系统镜像", args: { name: "文件|URL|- [仓库[:标签]]" } },
    { name: "search", description: "在 Docker Hub 中搜索镜像", args: { name: "关键字" }, options: [
      { name: ["-f", "--filter"], description: "按条件过滤输出", args: { name: "条件" } },
      { name: "--limit", description: "最大搜索结果数（默认 25）", args: { name: "数量" } },
      { name: "--no-trunc", description: "不截断输出" },
    ]},
    { name: "info", description: "显示系统范围的 Docker 信息", options: [
      { name: ["-f", "--format"], description: "使用 Go 模板格式化输出", args: { name: "模板" } },
    ]},
    { name: "version", description: "显示 Docker 版本信息", options: [
      { name: ["-f", "--format"], description: "格式化输出（pretty 或 json）", args: { name: "格式", suggestions: ["pretty", "json"] } },
    ]},
    { name: "login", description: "登录到 Docker 仓库", args: { name: "服务器", isOptional: true }, options: [
      { name: ["-u", "--username"], description: "用户名", args: { name: "用户名" } },
      { name: ["-p", "--password"], description: "密码", args: { name: "密码" } },
      { name: "--password-stdin", description: "从标准输入读取密码" },
    ]},
    { name: "logout", description: "从 Docker 仓库登出", args: { name: "服务器", isOptional: true } },
    { name: "events", description: "获取服务器的实时事件", options: [
      { name: ["-f", "--filter"], description: "按条件过滤输出", args: { name: "条件" } },
      { name: "--since", description: "显示该时间戳之后的事件", args: { name: "时间" } },
      { name: "--until", description: "流式输出直到该时间戳", args: { name: "时间" } },
    ]},
    { name: "container", description: "管理容器", subcommands: [
      { name: "ls", description: "列出容器" },
      { name: "inspect", description: "显示容器详细信息", args: { name: "容器" } },
      { name: "logs", description: "获取容器日志", args: { name: "容器" } },
      { name: "exec", description: "在运行中的容器内执行命令", args: { name: "容器" } },
      { name: "run", description: "在新容器中运行命令", args: { name: "镜像" } },
      { name: "start", description: "启动已停止的容器", args: { name: "容器", isVariadic: true } },
      { name: "stop", description: "停止运行中的容器", args: { name: "容器", isVariadic: true } },
      { name: "restart", description: "重启容器", args: { name: "容器", isVariadic: true } },
      { name: "kill", description: "杀死运行中的容器", args: { name: "容器", isVariadic: true } },
      { name: "rm", description: "删除容器", args: { name: "容器", isVariadic: true } },
      { name: "prune", description: "删除所有已停止的容器", options: [
        { name: ["-f", "--force"], description: "不提示确认" },
        { name: "--filter", description: "提供过滤条件", args: { name: "条件" } },
      ]},
      { name: "pause", description: "暂停容器内的所有进程", args: { name: "容器", isVariadic: true } },
      { name: "unpause", description: "恢复被暂停的进程", args: { name: "容器", isVariadic: true } },
      { name: "attach", description: "附加到运行中的容器", args: { name: "容器" } },
      { name: "cp", description: "在容器与本地之间复制文件", args: { name: "源路径 目标路径" } },
      { name: "diff", description: "检查容器文件系统变更", args: { name: "容器" } },
      { name: "export", description: "将容器文件系统导出为 tar", args: { name: "容器" } },
      { name: "port", description: "列出容器端口映射", args: { name: "容器" } },
      { name: "rename", description: "重命名容器", args: [{ name: "容器" }, { name: "新名称" }] },
      { name: "stats", description: "显示容器资源使用统计", args: { name: "容器", isOptional: true } },
      { name: "top", description: "显示容器中正在运行的进程", args: { name: "容器" } },
      { name: "update", description: "更新容器配置", args: { name: "容器", isVariadic: true } },
      { name: "wait", description: "等待容器停止并打印退出码", args: { name: "容器", isVariadic: true } },
      { name: "create", description: "创建一个新容器", args: { name: "镜像" } },
    ]},
    { name: "image", description: "管理镜像", subcommands: [
      { name: "ls", description: "列出镜像" },
      { name: "build", description: "根据 Dockerfile 构建镜像", args: { name: "路径", template: "folders" } },
      { name: "pull", description: "从仓库拉取镜像", args: { name: "镜像[:标签]" } },
      { name: "push", description: "将镜像推送到仓库", args: { name: "镜像[:标签]" } },
      { name: "rm", description: "删除一个或多个镜像", args: { name: "镜像", isVariadic: true } },
      { name: "tag", description: "为镜像创建标签", args: { name: "源镜像 目标镜像" } },
      { name: "inspect", description: "显示镜像详细信息", args: { name: "镜像", isVariadic: true } },
      { name: "history", description: "显示镜像历史层", args: { name: "镜像" } },
      { name: "save", description: "将镜像保存为 tar 归档", args: { name: "镜像", isVariadic: true } },
      { name: "load", description: "从 tar 归档加载镜像" },
      { name: "import", description: "从 tarball 导入文件系统镜像" },
      { name: "prune", description: "删除未使用的镜像", options: [
        { name: ["-a", "--all"], description: "删除所有未使用的镜像，不只是悬空镜像" },
        { name: ["-f", "--force"], description: "不提示确认" },
        { name: "--filter", description: "提供过滤条件", args: { name: "条件" } },
      ]},
    ]},
    { name: "network", description: "管理网络", subcommands: [
      { name: "ls", description: "列出网络" },
      { name: "create", description: "创建网络", args: { name: "网络" }, options: [
        { name: ["-d", "--driver"], description: "网络驱动（默认 bridge）", args: { name: "驱动" } },
        { name: "--subnet", description: "CIDR 格式的子网", args: { name: "子网" } },
        { name: "--gateway", description: "主子网网关", args: { name: "网关" } },
        { name: "--internal", description: "限制外部访问该网络" },
        { name: "--ipv6", description: "启用 IPv6 网络" },
      ]},
      { name: "rm", description: "删除一个或多个网络", args: { name: "网络", isVariadic: true } },
      { name: "inspect", description: "显示网络详细信息", args: { name: "网络", isVariadic: true } },
      { name: "connect", description: "将容器连接到网络", args: [{ name: "网络" }, { name: "容器" }] },
      { name: "disconnect", description: "将容器从网络断开", args: [{ name: "网络" }, { name: "容器" }] },
      { name: "prune", description: "删除所有未使用的网络", options: [
        { name: ["-f", "--force"], description: "不提示确认" },
      ]},
    ]},
    { name: "volume", description: "管理数据卷", subcommands: [
      { name: "ls", description: "列出数据卷" },
      { name: "create", description: "创建数据卷", args: { name: "卷名", isOptional: true }, options: [
        { name: ["-d", "--driver"], description: "指定卷驱动（默认 local）", args: { name: "驱动" } },
        { name: "--label", description: "为卷设置元数据", args: { name: "标签" } },
      ]},
      { name: "rm", description: "删除一个或多个数据卷", args: { name: "卷名", isVariadic: true }, options: [
        { name: ["-f", "--force"], description: "强制删除" },
      ]},
      { name: "inspect", description: "显示数据卷详细信息", args: { name: "卷名", isVariadic: true } },
      { name: "prune", description: "删除所有未使用的本地数据卷", options: [
        { name: ["-f", "--force"], description: "不提示确认" },
      ]},
    ]},
    { name: "system", description: "管理 Docker 系统", subcommands: [
      { name: "df", description: "显示 Docker 磁盘使用情况", options: [
        { name: ["-v", "--verbose"], description: "显示空间使用的详细信息" },
      ]},
      { name: "info", description: "显示系统范围的信息" },
      { name: "events", description: "获取服务器的实时事件" },
      { name: "prune", description: "删除未使用的数据", options: [
        { name: ["-a", "--all"], description: "删除所有未使用的镜像，不只是悬空镜像" },
        { name: ["-f", "--force"], description: "不提示确认" },
        { name: "--volumes", description: "同时清理数据卷" },
      ]},
    ]},
    { name: "compose", description: "使用 Docker 定义并运行多容器应用", subcommands: [
      { name: "up", description: "创建并启动服务", args: { name: "服务", isOptional: true, isVariadic: true }, options: [
        { name: ["-d", "--detach"], description: "在后台运行容器" },
        { name: "--build", description: "启动前构建镜像" },
        { name: "--force-recreate", description: "即使配置和镜像未变也重新创建容器" },
        { name: "--no-deps", description: "不启动链接的服务" },
        { name: "--remove-orphans", description: "删除 Compose 文件中未定义的服务容器" },
        { name: "--scale", description: "设置服务实例数量", args: { name: "服务=数量" } },
        { name: ["-V", "--renew-anon-volumes"], description: "重新创建匿名卷而不是沿用旧数据" },
      ]},
      { name: "down", description: "停止并删除容器、网络", options: [
        { name: ["-v", "--volumes"], description: "同时删除声明的数据卷和匿名卷" },
        { name: "--rmi", description: "删除使用的镜像", args: { name: "类型", suggestions: ["all", "local"] } },
        { name: "--remove-orphans", description: "删除 Compose 文件中未定义的服务容器" },
        { name: ["-t", "--timeout"], description: "关闭超时秒数", args: { name: "秒" } },
      ]},
      { name: "ps", description: "列出容器", args: { name: "服务", isOptional: true, isVariadic: true }, options: [
        { name: ["-a", "--all"], description: "显示已停止的容器" },
        { name: ["-q", "--quiet"], description: "只显示容器 ID" },
        { name: "--services", description: "显示服务" },
      ]},
      { name: "logs", description: "查看服务日志", args: { name: "服务", isOptional: true, isVariadic: true }, options: [
        { name: ["-f", "--follow"], description: "持续跟踪日志输出" },
        { name: ["-t", "--timestamps"], description: "显示时间戳" },
        { name: "--tail", description: "从日志末尾显示指定行数", args: { name: "行数" } },
        { name: "--no-color", description: "关闭彩色输出" },
      ]},
      { name: "exec", description: "在运行中的服务容器内执行命令", args: [
        { name: "服务" },
        { name: "命令", isVariadic: true },
      ], options: [
        { name: "-it", description: "交互式终端（-i 与 -t 的组合）" },
        { name: ["-i", "--interactive"], description: "保持 STDIN 打开" },
        { name: ["-t", "--tty"], description: "分配一个伪终端" },
        { name: ["-d", "--detach"], description: "在后台运行命令" },
        { name: ["-e", "--env"], description: "设置环境变量", args: { name: "KEY=VALUE" } },
        { name: ["-u", "--user"], description: "指定用户名或 UID", args: { name: "用户" } },
        { name: ["-w", "--workdir"], description: "设置工作目录", args: { name: "路径" } },
      ]},
      { name: "build", description: "构建或重新构建服务", args: { name: "服务", isOptional: true, isVariadic: true }, options: [
        { name: "--no-cache", description: "构建时不使用缓存" },
        { name: "--pull", description: "始终尝试拉取更新版本的镜像" },
        { name: ["-q", "--quiet"], description: "抑制构建输出" },
      ]},
      { name: "pull", description: "拉取服务镜像", args: { name: "服务", isOptional: true, isVariadic: true } },
      { name: "push", description: "推送服务镜像", args: { name: "服务", isOptional: true, isVariadic: true } },
      { name: "start", description: "启动服务", args: { name: "服务", isOptional: true, isVariadic: true } },
      { name: "stop", description: "停止服务", args: { name: "服务", isOptional: true, isVariadic: true } },
      { name: "restart", description: "重启服务", args: { name: "服务", isOptional: true, isVariadic: true } },
      { name: "pause", description: "暂停服务", args: { name: "服务", isOptional: true, isVariadic: true } },
      { name: "unpause", description: "恢复服务", args: { name: "服务", isOptional: true, isVariadic: true } },
      { name: "rm", description: "删除已停止的服务容器", args: { name: "服务", isOptional: true, isVariadic: true }, options: [
        { name: ["-f", "--force"], description: "不提示确认" },
        { name: ["-s", "--stop"], description: "删除前先停止容器" },
        { name: ["-v", "--volumes"], description: "同时删除匿名卷" },
      ]},
      { name: "run", description: "一次性运行服务命令", args: [
        { name: "服务" },
        { name: "命令", isOptional: true, isVariadic: true },
      ], options: [
        { name: ["-d", "--detach"], description: "在后台运行" },
        { name: "--rm", description: "退出后自动删除容器" },
        { name: ["-e", "--env"], description: "设置环境变量", args: { name: "KEY=VALUE" } },
        { name: ["-p", "--publish"], description: "发布端口", args: { name: "端口" } },
        { name: "--no-deps", description: "不启动链接的服务" },
      ]},
      { name: "config", description: "校验并查看 Compose 文件", options: [
        { name: ["-q", "--quiet"], description: "只校验，不打印" },
        { name: "--services", description: "打印服务名称" },
        { name: "--volumes", description: "打印卷名称" },
        { name: "--images", description: "打印镜像名称" },
      ]},
      { name: "create", description: "为服务创建容器", args: { name: "服务", isOptional: true, isVariadic: true } },
      { name: "images", description: "列出服务使用的镜像" },
      { name: "kill", description: "强制停止服务容器", args: { name: "服务", isOptional: true, isVariadic: true } },
      { name: "top", description: "显示服务中正在运行的进程", args: { name: "服务", isOptional: true } },
      { name: "cp", description: "在服务容器与本地之间复制文件", args: { name: "源路径 目标路径" } },
      { name: "ls", description: "列出正在运行的 Compose 项目" },
      { name: "version", description: "显示 Docker Compose 版本信息" },
    ], options: [
      { name: ["-f", "--file"], description: "指定 Compose 文件", args: { name: "文件", template: "filepaths" } },
      { name: ["-p", "--project-name"], description: "指定项目名称", args: { name: "名称" } },
      { name: "--profile", description: "启用指定配置文件", args: { name: "配置" } },
      { name: "--env-file", description: "指定环境变量文件", args: { name: "文件", template: "filepaths" } },
      { name: "--project-directory", description: "指定项目工作目录", args: { name: "路径", template: "folders" } },
    ]},
    { name: "context", description: "管理 Docker 上下文", subcommands: [
      { name: "ls", description: "列出可用上下文" },
      { name: "create", description: "创建新上下文", args: { name: "名称" } },
      { name: "use", description: "设置默认上下文", args: { name: "名称" } },
      { name: "show", description: "打印当前上下文" },
      { name: "inspect", description: "显示上下文详细信息", args: { name: "名称", isVariadic: true } },
      { name: "rm", description: "删除一个或多个上下文", args: { name: "名称", isVariadic: true } },
      { name: "update", description: "更新上下文", args: { name: "名称" } },
      { name: "export", description: "将上下文导出为 tar 或 kubeconfig 文件", args: [{ name: "名称" }, { name: "文件", isOptional: true }] },
      { name: "import", description: "从 tar 或 zip 文件导入上下文", args: [{ name: "名称" }, { name: "文件", template: "filepaths" }] },
    ]},
    { name: "builder", description: "管理构建", subcommands: [
      { name: "build", description: "根据 Dockerfile 构建镜像", args: { name: "路径", template: "folders" } },
      { name: "prune", description: "清理构建缓存", options: [
        { name: ["-a", "--all"], description: "删除所有未使用的构建缓存，不只是悬空缓存" },
        { name: ["-f", "--force"], description: "不提示确认" },
      ]},
    ]},
    { name: "buildx", description: "使用 BuildKit 扩展构建能力", subcommands: [
      { name: "build", description: "使用 BuildKit 构建", args: { name: "路径", template: "folders" } },
      { name: "ls", description: "列出构建器实例" },
      { name: "inspect", description: "查看当前构建器实例" },
      { name: "create", description: "创建新的构建器实例" },
      { name: "use", description: "设置当前构建器实例", args: { name: "名称" } },
      { name: "rm", description: "删除构建器实例", args: { name: "名称", isOptional: true } },
      { name: "prune", description: "清理构建缓存" },
      { name: "version", description: "显示 buildx 版本信息" },
    ]},
    { name: "plugin", description: "管理插件", subcommands: [
      { name: "ls", description: "列出插件" },
      { name: "install", description: "安装插件", args: { name: "插件" } },
      { name: "enable", description: "启用插件", args: { name: "插件" } },
      { name: "disable", description: "禁用插件", args: { name: "插件" } },
      { name: "rm", description: "删除一个或多个插件", args: { name: "插件", isVariadic: true } },
      { name: "inspect", description: "显示插件详细信息", args: { name: "插件", isVariadic: true } },
    ]},
    { name: "secret", description: "管理 Docker 密钥", subcommands: [
      { name: "ls", description: "列出密钥" },
      { name: "create", description: "从文件或 STDIN 创建密钥", args: [{ name: "名称" }, { name: "文件", isOptional: true, template: "filepaths" }] },
      { name: "inspect", description: "显示密钥详细信息", args: { name: "密钥", isVariadic: true } },
      { name: "rm", description: "删除一个或多个密钥", args: { name: "密钥", isVariadic: true } },
    ]},
    { name: "service", description: "管理 Swarm 服务", subcommands: [
      { name: "ls", description: "列出服务" },
      { name: "create", description: "创建新服务", args: { name: "镜像" } },
      { name: "inspect", description: "显示服务详细信息", args: { name: "服务", isVariadic: true } },
      { name: "logs", description: "获取服务或任务日志", args: { name: "服务或任务" } },
      { name: "ps", description: "列出一个或多个服务的任务", args: { name: "服务", isVariadic: true } },
      { name: "rm", description: "删除一个或多个服务", args: { name: "服务", isVariadic: true } },
      { name: "scale", description: "扩缩复制模式服务", args: { name: "服务=副本数", isVariadic: true } },
      { name: "update", description: "更新服务", args: { name: "服务" } },
      { name: "rollback", description: "回滚服务配置变更", args: { name: "服务" } },
    ]},
    { name: "stack", description: "管理 Docker 栈", subcommands: [
      { name: "deploy", description: "部署新栈或更新已有栈", args: { name: "栈" }, options: [
        { name: ["-c", "--compose-file"], description: "Compose 文件路径，或 “-” 表示从 stdin 读取", args: { name: "文件", template: "filepaths" } },
      ]},
      { name: "ls", description: "列出栈" },
      { name: "ps", description: "列出栈中的任务", args: { name: "栈" } },
      { name: "rm", description: "删除一个或多个栈", args: { name: "栈", isVariadic: true } },
      { name: "services", description: "列出栈中的服务", args: { name: "栈" } },
    ]},
    { name: "node", description: "管理 Swarm 节点", subcommands: [
      { name: "ls", description: "列出 Swarm 中的节点" },
      { name: "inspect", description: "显示节点详细信息", args: { name: "节点", isVariadic: true } },
      { name: "ps", description: "列出节点上运行的任务", args: { name: "节点", isOptional: true } },
      { name: "promote", description: "将一个或多个节点提升为 manager", args: { name: "节点", isVariadic: true } },
      { name: "demote", description: "将一个或多个节点降级为 worker", args: { name: "节点", isVariadic: true } },
      { name: "rm", description: "从 Swarm 中移除节点", args: { name: "节点", isVariadic: true } },
      { name: "update", description: "更新节点", args: { name: "节点" } },
    ]},
    { name: "swarm", description: "管理 Swarm 集群", subcommands: [
      { name: "init", description: "初始化 Swarm" },
      { name: "join", description: "以节点和/或 manager 身份加入 Swarm", args: { name: "HOST:PORT" } },
      { name: "leave", description: "离开 Swarm", options: [
        { name: ["-f", "--force"], description: "强制离开 Swarm，忽略警告" },
      ]},
      { name: "join-token", description: "管理加入令牌", args: { name: "角色", suggestions: ["worker", "manager"] } },
      { name: "update", description: "更新 Swarm" },
      { name: "unlock", description: "解锁 Swarm" },
      { name: "unlock-key", description: "管理解锁密钥" },
    ]},
  ],
  options: [
    { name: ["-H", "--host"], description: "Docker 守护进程的套接字", args: { name: "套接字" } },
    { name: ["-c", "--context"], description: "用于连接守护进程的上下文名称", args: { name: "名称" } },
    { name: "--config", description: "客户端配置文件所在目录", args: { name: "目录", template: "folders" } },
    { name: ["-D", "--debug"], description: "启用调试模式" },
    { name: ["-l", "--log-level"], description: "设置日志级别", args: { name: "级别", suggestions: ["debug", "info", "warn", "error", "fatal"] } },
    { name: "--tls", description: "启用 TLS" },
    { name: "--tlsverify", description: "使用 TLS 并验证远程" },
    { name: "--tlscacert", description: "仅由该 CA 签名的信任证书", args: { name: "文件", template: "filepaths" } },
    { name: "--tlscert", description: "TLS 证书文件路径", args: { name: "文件", template: "filepaths" } },
    { name: "--tlskey", description: "TLS 密钥文件路径", args: { name: "文件", template: "filepaths" } },
    { name: ["-v", "--version"], description: "打印版本信息并退出" },
    { name: ["-h", "--help"], description: "显示帮助信息" },
  ],
};

export default completionSpec;
