// journalctl 规范 — systemd 日志查询工具
const completionSpec = {
  name: "journalctl",
  description: "查询 systemd 日志",
  options: [
    { name: ["-f", "--follow"], description: "持续跟踪新的日志条目（类似 tail -f）" },
    { name: ["-r", "--reverse"], description: "先显示最新条目" },
    { name: ["-e", "--pager-end"], description: "跳转到日志末尾" },
    { name: "--no-pager", description: "不将输出通过分页器显示" },
    { name: ["-a", "--all"], description: "完整显示所有字段" },
    { name: ["-n", "--lines"], description: "显示的日志条目数量", args: { name: "行数", description: "行数" } },
    { name: ["-o", "--output"], description: "更改日志输出格式", args: { name: "格式", suggestions: ["short", "short-precise", "short-iso", "short-iso-precise", "short-full", "short-monotonic", "verbose", "export", "json", "json-pretty", "json-sse", "cat"] } },
    { name: ["-x", "--catalog"], description: "为日志行附加解释文本" },
    { name: ["-b", "--boot"], description: "显示指定启动的消息", args: { name: "启动ID", isOptional: true } },
    { name: ["-k", "--dmesg"], description: "只显示内核消息" },
    { name: ["-u", "--unit"], description: "显示指定单元的消息", args: { name: "单元" } },
    { name: "--user-unit", description: "显示指定用户单元的消息", args: { name: "单元" } },
    { name: ["-t", "--identifier"], description: "按 syslog 标识符过滤消息", args: { name: "标识符" } },
    { name: ["-p", "--priority"], description: "按消息优先级过滤", args: { name: "优先级", suggestions: ["emerg", "alert", "crit", "err", "warning", "notice", "info", "debug", "0", "1", "2", "3", "4", "5", "6", "7"] } },
    { name: ["-g", "--grep"], description: "按消息内容过滤（PCRE2 正则）", args: { name: "模式" } },
    { name: ["-S", "--since"], description: "显示该日期及之后的条目", args: { name: "日期", description: "如 '2023-01-01'、'yesterday'、'1 hour ago'" } },
    { name: ["-U", "--until"], description: "显示该日期及之前的条目", args: { name: "日期" } },
    { name: "--disk-usage", description: "显示所有日志文件占用的磁盘空间" },
    { name: "--vacuum-size", description: "将磁盘占用压缩到指定大小以下", args: { name: "字节" } },
    { name: "--vacuum-time", description: "删除早于指定时间的日志文件", args: { name: "时间" } },
    { name: "--list-boots", description: "列出各次启动记录" },
    { name: ["-D", "--directory"], description: "从指定目录读取日志文件", args: { name: "目录", template: "folders" } },
    { name: "--file", description: "操作指定的日志文件", args: { name: "文件", template: "filepaths" } },
    { name: "--no-hostname", description: "隐藏主机名字段" },
    { name: ["-q", "--quiet"], description: "抑制信息提示和权限警告" },
    { name: "--utc", description: "以 UTC 时间显示" },
    { name: "--system", description: "只显示系统日志" },
    { name: "--user", description: "只显示当前用户的用户日志" },
    { name: ["-h", "--help"], description: "显示帮助信息" },
  ],
};

export default completionSpec;
