// sbatch 规范 — SLURM 批作业提交
const completionSpec = {
  name: "sbatch",
  description: "向 SLURM 提交批处理作业脚本",
  args: [
    { name: "参数", description: "传递给脚本的参数", isOptional: true, isVariadic: true },
    { name: "脚本", description: "批处理脚本文件", template: "filepaths" },
  ],
  options: [
    { name: ["-A", "--account"], description: "作业记账账户", args: { name: "账户" } },
    { name: ["-J", "--job-name"], description: "作业名称", args: { name: "名称" } },
    { name: ["-p", "--partition"], description: "提交到指定分区", args: { name: "分区" } },
    { name: ["-q", "--qos"], description: "服务质量（QoS）", args: { name: "QoS" } },
    { name: ["-t", "--time"], description: "作业时限（如 1:00:00 或 60）", args: { name: "时间" } },
    { name: "--time-min", description: "最小可接受时限", args: { name: "时间" } },
    { name: ["-N", "--nodes"], description: "申请节点数（min[-max]）", args: { name: "节点数" } },
    { name: ["-n", "--ntasks"], description: "任务（进程）总数", args: { name: "数量" } },
    { name: "--ntasks-per-node", description: "每个节点的任务数", args: { name: "数量" } },
    { name: "--ntasks-per-core", description: "每个 CPU 核心的任务数", args: { name: "数量" } },
    { name: "--ntasks-per-socket", description: "每个 CPU 插槽的任务数", args: { name: "数量" } },
    { name: "--ntasks-per-gpu", description: "每个 GPU 的任务数", args: { name: "数量" } },
    { name: ["-c", "--cpus-per-task"], description: "每个任务分配的 CPU 数", args: { name: "数量" } },
    { name: "--cpus-per-gpu", description: "每个 GPU 分配的 CPU 数", args: { name: "数量" } },
    { name: "--mem", description: "每个节点的内存（如 8G、4096M）", args: { name: "大小" } },
    { name: "--mem-per-cpu", description: "每个 CPU 的内存", args: { name: "大小" } },
    { name: "--mem-per-gpu", description: "每个 GPU 的内存", args: { name: "大小" } },
    { name: ["-G", "--gpus"], description: "申请 GPU 数量（可带类型，如 a100:2）", args: { name: "数量" } },
    { name: "--gpus-per-node", description: "每个节点的 GPU 数量", args: { name: "数量" } },
    { name: "--gpus-per-task", description: "每个任务的 GPU 数量", args: { name: "数量" } },
    { name: "--gres", description: "通用资源（如 gpu:2）", args: { name: "资源" } },
    { name: ["-a", "--array"], description: "作业数组索引（如 0-31、1,3,5、0-15%4）", args: { name: "索引" } },
    { name: ["-d", "--dependency"], description: "依赖其他作业（afterok、afterany、aftercorr 等）", args: { name: "依赖" } },
    { name: ["-D", "--chdir"], description: "作业工作目录", args: { name: "目录", template: "folders" } },
    { name: ["-o", "--output"], description: "标准输出文件（可用 %j、%A、%a）", args: { name: "文件", template: "filepaths" } },
    { name: ["-e", "--error"], description: "标准错误文件", args: { name: "文件", template: "filepaths" } },
    { name: ["-i", "--input"], description: "标准输入文件", args: { name: "文件", template: "filepaths" } },
    { name: "--open-mode", description: "输出文件打开方式", args: { name: "模式", suggestions: ["append", "truncate"] } },
    { name: ["-w", "--nodelist"], description: "请求指定节点列表", args: { name: "节点列表" } },
    { name: ["-x", "--exclude"], description: "排除指定节点", args: { name: "节点列表" } },
    { name: "--constraint", description: "节点特征约束", args: { name: "约束" } },
    { name: "--prefer", description: "优先选择满足条件的节点", args: { name: "特征" } },
    { name: "--exclusive", description: "独占节点（不与其他作业共享）", args: { name: "模式", isOptional: true, suggestions: ["user", "mcs", "topo"] } },
    { name: "--oversubscribe", description: "允许与其他作业共享资源" },
    { name: ["-H", "--hold"], description: "提交后立即挂起作业" },
    { name: ["-b", "--begin"], description: "最早开始时间", args: { name: "时间" } },
    { name: "--deadline", description: "作业必须在此时间前结束", args: { name: "时间" } },
    { name: "--reservation", description: "使用指定预留", args: { name: "预留名" } },
    { name: "--comment", description: "作业注释", args: { name: "注释" } },
    { name: "--mail-type", description: "邮件通知类型", args: { name: "类型", suggestions: ["NONE", "BEGIN", "END", "FAIL", "REQUEUE", "ALL", "INVALID_DEPEND", "STAGE_OUT", "TIME_LIMIT", "TIME_LIMIT_90", "TIME_LIMIT_80", "TIME_LIMIT_50"] } },
    { name: "--mail-user", description: "接收通知的邮箱", args: { name: "邮箱" } },
    { name: "--export", description: "导出环境变量到作业（ALL、NONE 或变量列表）", args: { name: "变量" } },
    { name: "--export-file", description: "从文件读取要导出的环境变量", args: { name: "文件", template: "filepaths" } },
    { name: "--get-user-env", description: "在计算节点上加载用户登录环境" },
    { name: "--wrap", description: "将命令字符串包装成临时批处理脚本", args: { name: "命令" } },
    { name: ["-W", "--wait"], description: "等待作业结束后再退出" },
    { name: "--parsable", description: "只打印作业 ID，便于脚本解析" },
    { name: "--test-only", description: "只验证并估算开始时间，不真正提交" },
    { name: "--requeue", description: "节点失败时允许重新排队" },
    { name: "--no-requeue", description: "节点失败时禁止重新排队" },
    { name: "--kill-on-invalid-dep", description: "依赖无效时是否杀死作业", args: { name: "yes|no", suggestions: ["yes", "no"] } },
    { name: ["-L", "--licenses"], description: "申请许可证资源", args: { name: "许可证" } },
    { name: ["-M", "--clusters"], description: "向指定集群提交", args: { name: "集群" } },
    { name: "--nice", description: "降低或提高调度优先级（正数更低）", args: { name: "调整值", isOptional: true } },
    { name: "--priority", description: "请求特定优先级", args: { name: "优先级" } },
    { name: "--signal", description: "时限到期前向作业发送信号", args: { name: "信号[@秒]" } },
    { name: "--distribution", description: "任务在节点/插槽/核心上的分布方式", args: { name: "方式", suggestions: ["block", "cyclic", "plane", "arbitrary"] } },
    { name: "--hint", description: "绑定提示", args: { name: "类型", suggestions: ["compute_bound", "memory_bound", "multithread", "nomultithread"] } },
    { name: "--cpu-bind", description: "CPU 绑定策略", args: { name: "策略" } },
    { name: "--mem-bind", description: "内存绑定策略", args: { name: "策略" } },
    { name: "--gpu-bind", description: "GPU 绑定策略", args: { name: "策略" } },
    { name: "--sockets-per-node", description: "每个节点需要的 CPU 插槽数", args: { name: "数量" } },
    { name: "--cores-per-socket", description: "每个插槽需要的核心数", args: { name: "数量" } },
    { name: "--threads-per-core", description: "每个核心需要的线程数", args: { name: "数量" } },
    { name: "--tmp", description: "每个节点的临时磁盘空间", args: { name: "大小" } },
    { name: "--wckey", description: "工作负载特征键", args: { name: "键" } },
    { name: "--container", description: "在指定容器中运行作业", args: { name: "路径" } },
    { name: ["-k", "--no-kill"], description: "某个节点失败时不要终止整个作业" },
    { name: ["-Q", "--quiet"], description: "安静模式" },
    { name: ["-v", "--verbose"], description: "详细模式" },
    { name: ["-V", "--version"], description: "显示版本信息" },
    { name: ["-h", "--help"], description: "显示帮助信息" },
  ],
};

export default completionSpec;
