// scontrol 规范 — SLURM 配置与状态管理
const completionSpec = {
  name: "scontrol",
  description: "查看和修改 SLURM 配置与作业/节点状态",
  subcommands: [
    { name: "show", description: "显示指定实体的信息", subcommands: [
      { name: "job", description: "显示作业信息", args: { name: "作业ID", isOptional: true, isVariadic: true } },
      { name: "jobs", description: "显示作业信息（job 的别名）", args: { name: "作业ID", isOptional: true, isVariadic: true } },
      { name: "step", description: "显示作业步信息", args: { name: "作业ID.步ID", isOptional: true } },
      { name: "node", description: "显示节点信息", args: { name: "节点名", isOptional: true, isVariadic: true } },
      { name: "nodes", description: "显示节点信息（node 的别名）", args: { name: "节点名", isOptional: true, isVariadic: true } },
      { name: "partition", description: "显示分区信息", args: { name: "分区", isOptional: true } },
      { name: "partitions", description: "显示分区信息（partition 的别名）", args: { name: "分区", isOptional: true } },
      { name: "reservation", description: "显示预留信息", args: { name: "预留名", isOptional: true } },
      { name: "reservations", description: "显示预留信息（reservation 的别名）", args: { name: "预留名", isOptional: true } },
      { name: "config", description: "显示 SLURM 配置" },
      { name: "daemons", description: "显示本节点上的 SLURM 守护进程" },
      { name: "slurmd", description: "显示 slurmd 状态", args: { name: "节点名", isOptional: true } },
      { name: "hostnames", description: "将主机列表展开为主机名", args: { name: "主机列表", isOptional: true } },
      { name: "hostlist", description: "将主机名压缩为主机列表表达式", args: { name: "主机名", isVariadic: true } },
      { name: "hostlistsorted", description: "压缩为主机列表并按名称排序", args: { name: "主机名", isVariadic: true } },
      { name: "aliases", description: "显示节点别名" },
      { name: "assoc", description: "显示关联（association）信息" },
      { name: "licenses", description: "显示许可证信息" },
      { name: "topology", description: "显示网络拓扑", args: { name: "节点名", isOptional: true } },
      { name: "frontend", description: "显示前端节点信息" },
      { name: "burstbuffer", description: "显示突发缓冲（Burst Buffer）状态" },
      { name: "federation", description: "显示联邦集群信息" },
    ]},
    { name: "update", description: "更新作业、节点、分区或预留的属性", args: { name: "规格", description: "如 JobId=123 TimeLimit=2:00:00", isVariadic: true } },
    { name: "hold", description: "挂起作业（用户挂起）", args: { name: "作业ID", isVariadic: true } },
    { name: "uhold", description: "以用户身份挂起作业", args: { name: "作业ID", isVariadic: true } },
    { name: "release", description: "解除作业挂起", args: { name: "作业ID", isVariadic: true } },
    { name: "requeue", description: "将作业重新放入队列", args: { name: "作业ID", isVariadic: true } },
    { name: "requeuehold", description: "重新排队并立即挂起", args: { name: "作业ID", isVariadic: true } },
    { name: "suspend", description: "挂起（暂停）正在运行的作业", args: { name: "作业ID", isVariadic: true } },
    { name: "resume", description: "恢复被暂停的作业", args: { name: "作业ID", isVariadic: true } },
    { name: "top", description: "将作业提升到队列顶部（需权限）", args: { name: "作业ID", isVariadic: true } },
    { name: "notify", description: "向作业发送消息", args: [
      { name: "作业ID" },
      { name: "消息", isVariadic: true },
    ]},
    { name: "wait_job", description: "等待作业的所有节点完成启动", args: { name: "作业ID" } },
    { name: "pidinfo", description: "根据进程 PID 查找对应作业信息", args: { name: "PID" } },
    { name: "listpids", description: "列出作业相关进程 PID", args: [
      { name: "作业ID[.步ID]", isOptional: true },
      { name: "节点名", isOptional: true },
    ]},
    { name: "create", description: "创建预留或其他实体", args: { name: "规格", description: "如 ReservationName=... StartTime=... Duration=...", isVariadic: true } },
    { name: "delete", description: "删除预留或其他实体", args: { name: "规格", description: "如 ReservationName=...", isVariadic: true } },
    { name: "write", description: "写出批处理脚本或配置", subcommands: [
      { name: "batch_script", description: "写出指定作业的批处理脚本", args: [
        { name: "作业ID" },
        { name: "文件", isOptional: true, template: "filepaths" },
      ]},
      { name: "config", description: "写出当前 SLURM 配置", args: { name: "文件", isOptional: true, template: "filepaths" } },
    ]},
    { name: "reboot", description: "重启计算节点", args: { name: "节点列表", isOptional: true }, options: [
      { name: "ASAP", description: "作业结束后尽快重启" },
      { name: "nextstate", description: "重启后的节点状态", args: { name: "状态", suggestions: ["RESUME", "DOWN"] } },
      { name: "reason", description: "重启原因", args: { name: "原因" } },
    ]},
    { name: "cancel_reboot", description: "取消待执行的节点重启", args: { name: "节点列表", isOptional: true } },
    { name: "reconfigure", description: "让控制器重新读取配置文件" },
    { name: "ping", description: "探测 slurmctld 是否存活" },
    { name: "version", description: "显示 scontrol 版本" },
    { name: "shutdown", description: "关闭 slurmctld", args: { name: "模式", isOptional: true, suggestions: ["suspend"] } },
    { name: "takeover", description: "让备份控制器接管", args: { name: "索引", isOptional: true } },
    { name: "abort", description: "中止 slurmctld 并生成 core" },
    { name: "completing", description: "显示正在完成的作业" },
    { name: "token", description: "生成 JWT 认证令牌", args: { name: "参数", isOptional: true, isVariadic: true } },
    { name: "setdebug", description: "设置 slurmctld 调试级别", args: { name: "级别", suggestions: ["quiet", "fatal", "error", "info", "verbose", "debug", "debug2", "debug3", "debug4", "debug5"] } },
    { name: "setdebugflags", description: "设置或清除调试标志", args: { name: "+|-标志" } },
    { name: "schedloglevel", description: "设置调度器日志级别", args: { name: "级别" } },
    { name: "errnumstr", description: "将错误码转换为说明文字", args: { name: "错误码" } },
    { name: "help", description: "显示帮助", args: { name: "命令", isOptional: true } },
  ],
  options: [
    { name: ["-a", "--all"], description: "显示所有分区上的作业（含隐藏分区）" },
    { name: ["-d", "--details"], description: "显示更详细的信息" },
    { name: ["-F", "--future"], description: "同时报告未来节点" },
    { name: ["-o", "--oneliner"], description: "每条记录输出为一行" },
    { name: ["-M", "--cluster"], description: "指定集群", args: { name: "集群" } },
    { name: ["-u", "--uid"], description: "以指定用户身份更新作业", args: { name: "用户" } },
    { name: "--federation", description: "报告联邦中所有集群的信息" },
    { name: "--local", description: "只报告本地集群（与 --federation 相对）" },
    { name: "--sibling", description: "在联邦中移除同级作业信息" },
    { name: ["-Q", "--quiet"], description: "安静模式" },
    { name: ["-v", "--verbose"], description: "详细模式" },
    { name: ["-V", "--version"], description: "显示版本信息" },
    { name: ["-h", "--help"], description: "显示帮助信息" },
  ],
};

export default completionSpec;
