// yum 规范 — Yellowdog Updater Modified (RPM 软件包管理器)
const completionSpec = {
  name: "yum",
  description: "RPM 软件包管理器 (RHEL/CentOS)",
  subcommands: [
    { name: "install", description: "安装软件包", args: { name: "软件包", isVariadic: true } },
    { name: "remove", description: "卸载软件包", args: { name: "软件包", isVariadic: true } },
    { name: "update", description: "更新软件包", args: { name: "软件包", isOptional: true, isVariadic: true } },
    { name: "upgrade", description: "升级软件包（等同于 update --obsoletes）", args: { name: "软件包", isOptional: true, isVariadic: true } },
    { name: "downgrade", description: "降级软件包", args: { name: "软件包", isVariadic: true } },
    { name: "list", description: "列出软件包", subcommands: [
      { name: "installed", description: "列出已安装的软件包" },
      { name: "available", description: "列出可用的软件包" },
      { name: "updates", description: "列出可更新的软件包" },
      { name: "extras", description: "列出不在任何仓库中的已安装软件包" },
      { name: "obsoletes", description: "列出已被废弃的软件包" },
      { name: "all", description: "列出所有软件包" },
    ]},
    { name: "search", description: "通过关键字搜索包详情", args: { name: "关键字", isVariadic: true } },
    { name: "info", description: "显示软件包详情", args: { name: "软件包", isVariadic: true } },
    { name: "provides", description: "查找哪个软件包提供了某个文件/功能", args: { name: "功能" } },
    { name: "clean", description: "清理缓存数据", subcommands: [
      { name: "all", description: "清理所有缓存数据" },
      { name: "packages", description: "清理缓存的软件包" },
      { name: "metadata", description: "清理缓存的元数据" },
      { name: "dbcache", description: "清理数据库缓存数据" },
      { name: "expire-cache", description: "使缓存过期" },
    ]},
    { name: "makecache", description: "生成元数据缓存" },
    { name: "groupinstall", description: "安装软件包组", args: { name: "组" } },
    { name: "groupremove", description: "删除软件包组", args: { name: "组" } },
    { name: "grouplist", description: "列出可用的软件包组" },
    { name: "groupinfo", description: "显示软件包组详情", args: { name: "组" } },
    { name: "check-update", description: "检查可用的软件包更新" },
    { name: "reinstall", description: "重新安装软件包", args: { name: "软件包", isVariadic: true } },
    { name: "localinstall", description: "安装本地 RPM 软件包", args: { name: "rpm文件", template: "filepaths" } },
    { name: "deplist", description: "列出软件包依赖", args: { name: "软件包" } },
    { name: "repolist", description: "显示已配置的软件源", subcommands: [
      { name: "all", description: "列出所有源" },
      { name: "enabled", description: "列出启用的源" },
      { name: "disabled", description: "列出已禁用的源" },
    ]},
    { name: "repoinfo", description: "显示仓库信息" },
    { name: "history", description: "查看和管理 yum 事务历史", subcommands: [
      { name: "list", description: "列出事务" },
      { name: "info", description: "显示事务详情", args: { name: "编号" } },
      { name: "undo", description: "撤销某个事务", args: { name: "编号" } },
      { name: "redo", description: "重做某个事务", args: { name: "编号" } },
    ]},
    { name: "autoremove", description: "移除作为依赖安装但已不需要的软件包" },
  ],
  options: [
    { name: "-y", description: "全部回答“是”以自动进行操作" },
    { name: "-q", description: "安静模式" },
    { name: "-v", description: "详细模式" },
    { name: "--enablerepo", description: "启用一个仓库", args: { name: "仓库" } },
    { name: "--disablerepo", description: "禁用一个仓库", args: { name: "仓库" } },
    { name: "--nogpgcheck", description: "关闭GPG签名检查" },
    { name: "--skip-broken", description: "跳过依赖问题的软件包" },
    { name: "--showduplicates", description: "显示仓库中重复的软件包" },
    { name: "--installroot", description: "设置安装根目录", args: { name: "路径", template: "folders" } },
    { name: "-C", description: "完全从系统缓存中运行" },
    { name: "--security", description: "只包括与安全相关的软件包" },
    { name: ["-h", "--help"], description: "显示帮助信息" },
  ],
};

export default completionSpec;
